name: Sun-Panel
services:
  sun-panel:
    image: hslr/sun-panel:latest
    container_name: sun-panel
    tty: true
    # 自动启动
    restart: always
    privileged: true
    volumes:
      - /DATA/AppData/sun-panel/conf:/app/conf
      - /DATA/AppData/sun-panel/runtime:/app/runtime
      - /DATA/AppData/sun-panel/uploads:/app/uploads
      - /DATA/AppData/sun-panel/database:/app/database
    ports:
      - 3002:3002
    environment:
      - TZ=Asia/Shanghai
x-casaos:
  architectures:
    - amd64
  author: CasaOS User
  category: unknown
  description:
    en_us: ""
    zh_cn: ""
  developer: unknown
  icon: https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/SunPanel/icon/logo.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/SunPanel/images/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/SunPanel/images/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/SunPanel/images/screenshot-3.png
    - https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/SunPanel/images/screenshot-4.png
    - https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/SunPanel/images/screenshot-5.png
    - https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/SunPanel/images/screenshot-6.png
  main: Sun-Panel
  port_map: "3002"
  scheme: http
  tagline:
    en_us: "A server, NAS navigation panel, Homepage, browser homepage."
    zh_cn: "一个服务器、NAS导航面板、Homepage、浏览器首页。"
  thumbnail: ""
  tips:
    before_install:
      en_us: |
        | username | password |
        | -------- | -------- |
        | `admin@sun.cc` | `12345678` |
      zh_cn: |
        | 用户名 | 密码 |
        | -------- | -------- |
        | `admin@sun.cc` | `12345678` |
  title:
    en_us: Sun-Panel
