name: moviepilot
services:
  moviepilot:
    image: jxxghp/moviepilot:latest
    container_name: moviepilot
    network_mode: bridge
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
      - target: 3001
        published: "3001"
        protocol: tcp
    privileged: true
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/moviepilot/config
        target: /config
      - type: bind
        source: /DATA/AppData/moviepilot/qBittorrent/downloads
        target: /media/downloads/qBittorrent
      - type: bind
        source: /DATA/AppData/moviepilot/transmission/downloads
        target: /media/downloads/transmission
      - type: bind
        source: /DATA/AppData/moviepilot/moviepilot
        target: /moviepilot
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /DATA/AppData/qbittorrent/config/data/BT_backup
        target: /DATA/AppData/qbittorrent/config/data/BT_backup
      - type: bind
        source: /DATA/AppData/moviepilot/plugins
        target: /app/app/plugins
    environment:
      - TZ=Asia/Shanghai
      - PUID=0
      - PGID=0
      # 掩码权限，默认000，可以考虑设置为022（仅支持环境变量配置）
      - UMASK=000
      # 重启更新，true/false，默认true
      - MOVIEPILOT_AUTO_UPDATE=true
      # 重启时更新到未发布的开发版本代码，true/false，默认false（仅支持环境变量配置）
      - MOVIEPILOT_AUTO_UPDATE_DEV=false
      # 启动时自动检测和更新资源包（站点索引及认证等），true/false，默认true，需要能正常连接Github，仅支持Docker
      - AUTO_UPDATE_RESOURCE=true
      # API服务端口，默认3001，可自行修改，不能与WEB服务端口冲突（仅支持环境变量配置）
      - PORT=3001
      # WEB服务端口，默认3000，可自行修改，不能与API服务端口冲突（仅支持环境变量配置）
      - NGINX_PORT=3000
      # 网络代理，访问themoviedb或者重启更新需要使用代理访问，格式为http(s)://ip:port、socks5://user:pass@host:port
      - PROXY_HOST=
      # 认证站点（认证通过后才能使用站点相关功能），支持配置多个认证站点，使用,分隔，如：iyuu,hhclub，会依次执行认证操作，直到有一个站点认证成功。
      # 配置AUTH_SITE后，需要根据下表配置对应站点的认证参数，认证资源v1.1.1支持
      # iyuu/hhclub/audiences/hddolby/zmpt/freefarm/hdfans/wintersakura/leaves/ptba：1ptba /icc2022/ptlsp/xingtan/ptvicomo/agsvpt
      - AUTH_SITE=
	  # 自动更新
      - MOVIEPILOT_AUTO_UPDATE=release
	  # 超级管理员
      - SUPERUSER=admin
	  # API密钥，默认moviepilot，在媒体服务器Webhook、微信回调等地址配置中需要加上?token=该值，建议修改为复杂字符串
      - API_TOKEN=moviepilot
	  # 大内存模式，默认为false，开启后会增加缓存数量，占用更多的内存，但响应速度会更快
      - BIG_MEMORY_MODE=false
	  # Github token，提高自动更新、插件安装等请求Github Api的限流阈值，格式：ghp_****
      - GITHUB_TOKEN=
	  # 启动时自动检测和更新资源包（站点索引及认证等），true/false，默认true，需要能正常连接Github，仅支持Docker镜像
      - AUTO_UPDATE_RESOURCE=true
	  # TMDB API地址，默认api.themoviedb.org，也可配置为api.tmdb.org、tmdb.movie-pilot.org 或其它中转代理服务地址，能连通即可
      - TMDB_API_DOMAIN=api.themoviedb.org
	  # MDB图片地址，默认image.tmdb.org，可配置为其它中转代理以加速TMDB图片显示，如：static-mdb.v.geilijiasu.com
      - TMDB_IMAGE_DOMAIN=image.tmdb.org
	  # 登录首页电影海报，tmdb/bing，默认tmdb
      - WALLPAPER=tmdb
	  # 媒体信息识别来源，themoviedb/douban，默认themoviedb，使用douban时不支持二级分类
      - RECOGNIZE_SOURCE=themoviedb
	  # Fanart开关，true/false，默认true，关闭后刮削的图片类型会大幅减少
      - FANART_ENABLE=true
	  # 刮削元数据及图片使用的数据源，themoviedb/douban，默认themoviedb
      - SCRAP_SOURCE=themoviedb
	  # 新增已入库媒体是否跟随TMDB信息变化，true/false，默认true，为false时即使TMDB信息变化了也会仍然按历史记录中已入库的信息进行刮削
      - SCRAP_FOLLOW_TMDB=true
	  # OCR识别服务器地址，格式：http(s)://ip:port，用于识别站点验证码实现自动登录获取Cookie等，不配置默认使用内建服务器https://movie-pilot.org，可使用 这个镜像 自行搭建。
      - OCR_HOST=https://movie-pilot.org
	  # 下载站点字幕，true/false，默认true
      - DOWNLOAD_SUBTITLE=true
	  # 插件市场仓库地址，仅支持Github仓库main分支，多个地址使用,分隔，默认为官方插件仓库：https://github.com/jxxghp/MoviePilot-Plugins ，通过查看MoviePilot-Plugins项目的fork，或者查看频道置顶了解更多第三方插件仓库。
      - PLUGIN_MARKET=https://github.com/jxxghp/MoviePilot-Plugins
x-casaos:
  ports:
    - container: "3000"
      description:
        en_us: "Web interface access port"
        zh_cn: "web界面访问端口"
    - container: "3001"
      description:
        en_us: "API access port"
        zh_cn: "API访问端口"
  volumes:
    - container: /config
      description:
        en_us: "Configuration file storage directory"
        zh_cn: "配置文件存储目录"
    - container: /media/downloads/qBittorrent
      description:
        en_us: "Media file storage directory"
        zh_cn: "媒体文件存储目录"
    - container: /media/downloads/transmission
      description:
        en_us: "Media file storage directory"
        zh_cn: "媒体文件存储目录"
    - container: /moviepilot
      description:
        en_us: "Browser kernel storage directory, mapped to prevent duplicate kernel downloads"
        zh_cn: "浏览器内核存储目录，映射后可防止重复下载内核"
    - container: /var/run/docker.sock
      description:
        en_us: ""
        zh_cn: ""
    - container: /DATA/AppData/qbittorrent/config/data/BT_backup
      description:
        en_us: "QBittorrent seed file storage directory"
        zh_cn: "qBittorrent种子文件存储目录"
    - container: /app/app/plugins
      description:
        en_us: "Plugin directory, used to solve bugs where plugins cannot be downloaded properly"
        zh_cn: "插件目录，用于解决插件无法正常下载的BUG"
  architectures:
    - amd64
  author: CasaOS User
  category: WEB
  description:
    en_us: "This is an automated movie and video tracking service that can complete a series of movie and television resource management needs such as fully automated subscription, download, and scraping."
    zh_cn: "这是一个影音自动化追剧服务，能够完成全自动化的订阅、下载、刮削等一系列的影视资源管理需求。"
  developer: mattoid
  main: moviepilot
  port_map: "3000"
  scheme: http
  tagline:
    en_us: "NAS Media Library Automation Management Tool"
    zh_cn: "NAS媒体库自动化管理工具"
  thumbnail: ""
  title:
    en_us: moviepilot
  icon: https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/MoviePilot/icon/logo.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/MoviePilot/images/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/MoviePilot/images/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/MoviePilot/images/screenshot-3.png
    - https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/MoviePilot/images/screenshot-4.png
    - https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/MoviePilot/images/screenshot-5.png
    - https://cdn.jsdelivr.net/gh/Mattoids/casaos-store@master/Apps/MoviePilot/images/screenshot-6.png
  tips:
    before_install:
      en_us: |
        | username | password |
        | -------- | -------- |
        | `admin` | `password` |
      zh_cn: |
        | 用户名 | 密码 |
        | -------- | -------- |
        | `admin` | `password` |
